# Generated by Django 3.1.2 on 2020-10-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_QA', '0003_auto_20201018_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
    ]
